#profile dev
server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_ACCESS_EXP_MS}
      refresh-token:
        expiration: ${JWT_REFRESH_EXP_MS}
    cookie:
      secure: true
      same-site: Lax
cloud:
  aws:
    bucket:
      name: ${AWS_BUCKET_NAME}
    region:
      static: ${AWS_REGION_STATIC}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}